### ISSUE TITLE
Testing Error: Cannot find module 'eth-ens-namehash' on 

### ISSUE THREAD

**Issue by maurelian** [ethereum/ens#141]
`eth-ens-namehash` is installed, but: 
 
```
$ npm ls eth-ens-namehash
ens@0.1.1 /Users/primary/Projects/ens-project/security-review/ens-review
└── eth-ens-namehash@1.0.2

$ node -v
v6.9.1

$ truffle test --network test
Using network 'test'.

Compiling ./contracts/AbstractENS.sol...
Compiling ./contracts/DNSResolver.sol...
Compiling ./contracts/ENS.sol...
Compiling ./contracts/FIFSRegistrar.sol...
Compiling ./contracts/HashRegistrarSimplified.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/PublicResolver.sol...
Compiling ./contracts/ResolverInterface.sol...
Compiling ./contracts/ReverseRegistrar.sol...
Compiling ./contracts/TestRegistrar.sol...
/Users/primary/Projects/ens-project/security-review/ens-review/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=n

Error: Cannot find module 'eth-ens-namehash'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at require (/Users/primary/.nvm/versions/node/v6.9.1/lib/node_modules/truffle/node_modules/truffle-require/index.js:71:20)
    at /Users/primary/Projects/ens-project/security-review/ens-review/migrations/2_deploy_contracts.js:10:18
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at /Users/primary/.nvm/versions/node/v6.9.1/lib/node_modules/truffle/node_modules/truffle-require/index.js:90:14
    at tryToString (fs.js:455:3)
```

**Comment by maurelian** [comment]
I previously had the error with node 7.5 then tried moving down to 6.9. I'm guessing it's something related to truffle interfering with the require paths?

**Comment by Arachnid** [comment]
Hm. Have you tried wiping out the node_modules directory and starting again?

**Comment by Arachnid** [comment]
FWIW, `npm test` is still the canonical way to run the tests.

**Comment by maurelian** [comment]
Ahh, that was it. `npm test` works.
